### ISSUE TITLE
create an user_profile organism

### ISSUE THREAD

**Issue by shunei4517** [shunei4517/oz#4]
# goal
- display user profile including name, avatar and status message

# tasks
- [ ] receive an image url
- [ ] place the floating avatar on the top of card
- [ ] display status message
